# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main
# if you want to use it for any branch we will use "*"

resources:
- repo: self

variables:
  imageName: 'image-$(Build.Repository.Name):$(Build.SourceBranchName)-$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image & Deploy
  jobs:
  - job: Build
    displayName: Build & Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    
    - task: Docker@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'qammar3083'
        azureContainerRegistry: '{"loginServer":"yamlbased.azurecr.io", "id" : "/subscriptions/31a20a99-7ef9-42d8-9284-faa7cf41169e/resourceGroups/YamlTest/providers/Microsoft.ContainerRegistry/registries/yamlbased"}'
        action: 'Build an image'
        dockerFile: '$(build.sourcesDirectory)/Dockerfile'
        imageName: '$(imageName)'
        
    - task: Docker@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'qammar3083'
        azureContainerRegistry: '{"loginServer":"yamlbased.azurecr.io", "id" : "/subscriptions/31a20a99-7ef9-42d8-9284-faa7cf41169e/resourceGroups/YamlTest/providers/Microsoft.ContainerRegistry/registries/yamlbased"}'
        action: 'Push an image'
        imageName: '$(imageName)'   

    
 